# Step-by-Step Uncovering Apple Product Trends

## Introduction

📌 Purpose of Analysis
The purpose of this analysis is to gain insights into pricing, discount strategies, customer engagement, and product performance across various Apple products. Using Python, we explore key attributes such as sale price, MRP, discount percentage, star rating, number of reviews, and RAM specifications to:

Identify top discounted products and pricing trends

Evaluate brand-wise product performance

Understand customer preferences based on ratings and reviews

Uncover correlations between pricing, ratings, and technical specs

This data-driven approach supports better decision-making for marketing, pricing optimization, and inventory planning.

## 1. Reading the csv file  (apple_products_usd.csv)

In [6]:
import pandas as pd


In [8]:
df = pd.read_csv("https://raw.githubusercontent.com/your-username/Portfolio/main/01_iPhone_Data_Analysis/data/apple_products_usd.csv")


In [9]:
# below funtion will print first five rows of the csv file
df.head()

Product Name  Brand  SalePriceUSD  MrpUSD  \
0         APPLE iPhone 8 Plus (Gold, 64 GB)  Apple           582     582   
1  APPLE iPhone 8 Plus (Space Grey, 256 GB)  Apple           990     990   
2      APPLE iPhone 8 Plus (Silver, 256 GB)  Apple           990     990   
3           APPLE iPhone 8 (Silver, 256 GB)  Apple           898     898   
4             APPLE iPhone 8 (Gold, 256 GB)  Apple           898     898   

   Discount Percentage  Number Of Ratings  Number Of Reviews  \
0                    0               3431                356   
1                    0               3431                356   
2                    0               3431                356   
3                    0              11202                794   
4                    0              11202                794   

                Upc  Star Rating   Ram  
0  MOBEXRGV7EHHTGUH          4.6  2 GB  
1  MOBEXRGVAC6TJT4F          4.6  2 GB  
2  MOBEXRGVGETABXWZ          4.6  2 GB  
3  MOBEXRGVMZWUHCBA          4.5  2 GB  
4  MOBEXRGVPK7PFEJZ          4.5  2 GB

 Calculating the total rows for each column

## 2.  Checking the Number of Records per Column

In [10]:
# Lets find out how big is the file

df.count()

Product Name           62
Brand                  62
SalePriceUSD           62
MrpUSD                 62
Discount Percentage    62
Number Of Ratings      62
Number Of Reviews      62
Upc                    62
Star Rating            62
Ram                    62
dtype: int64

## 3. Identifying the Highest Listed Price (MRP) in USD

In [11]:
#lets find out the highest MRP (all prices are tagged in USD)

df['MrpUSD'].max()

1747

## 4. Identifying the Lowest Listed Price (MRP) in USD

In [12]:
#lets find out the lowest or minimum MRP (all prices are tagged in USD)

df['MrpUSD'].min()

465

## 5. Finding the iPhone Model with the Highest MRP

This code identifies the iPhone that was listed at the highest manufacturer retail price (MRP) in the dataset. By filtering the DataFrame for the maximum MRP value (1747.0 USD), I retrieve the full product details — including the product name, brand, rating, and other attributes — for the highest-priced iPhone.

In [13]:
#Lets figuer out which iphone was sold at the highest price (meaning Product name)

df[df['MrpUSD']==1747.0] 

Product Name  Brand  SalePriceUSD  MrpUSD  \
24        APPLE iPhone 12 Pro (Silver, 512 GB)  Apple          1642    1747   
41  APPLE iPhone 12 Pro (Pacific Blue, 512 GB)  Apple          1642    1747   

    Discount Percentage  Number Of Ratings  Number Of Reviews  \
24                    6                542                 42   
41                    6                545                 42   

                 Upc  Star Rating   Ram  
24  MOBFWBYZ5UY6ZBVA          4.5  4 GB  
41  MOBFWBYZTHSXKMGW          4.5  4 GB

## 6. Finding the iPhone Model with the Lowest MRP

This code is used to find the iPhone that was listed at the lowest manufacturer retail price (MRP) in the dataset. By filtering the DataFrame for the minimum MRP value (465.0 USD), I extract the complete product details — including the product name, brand, rating, and specifications — for the most affordable iPhone in the dataset.

In [14]:
#Lets figuer out which iphone was sold at the lowest price (meaning Product name)

df[df['MrpUSD']==465.0]

Product Name  Brand  SalePriceUSD  MrpUSD  \
52  APPLE iPhone SE (White, 64 GB)  Apple           350     465   
57  APPLE iPhone SE (Black, 64 GB)  Apple           350     465   

    Discount Percentage  Number Of Ratings  Number Of Reviews  \
52                   24              95807               8154   
57                   24              95909               8161   

                 Upc  Star Rating   Ram  
52  MOBFWQ6BGWDVGF3E          4.5  2 GB  
57  MOBFWQ6BR3MK7AUG          4.5  4 GB

## 7. Listing All iPhones Priced Below 600 USD (MRP)

This code filters the dataset to identify all iPhone models with a manufacturer retail price (MRP) less than or equal to 600 USD. I use this to explore more budget-friendly options and analyze the features, ratings, and other details of lower-priced iPhones.

In [15]:
# Lets see if you want to find out which are all iphone that has MRP < 500 USD

df[df['MrpUSD']<=600.0]

Product Name  Brand  SalePriceUSD  \
0                   APPLE iPhone 8 Plus (Gold, 64 GB)  Apple           582   
5                 APPLE iPhone 8 Plus (Silver, 64 GB)  Apple           582   
6             APPLE iPhone 8 Plus (Space Grey, 64 GB)  Apple           582   
10  Apple iPhone XR (Black, 64 GB) (Includes EarPo...  Apple           466   
52                     APPLE iPhone SE (White, 64 GB)  Apple           350   
53                    APPLE iPhone SE (Black, 128 GB)  Apple           408   
54                    APPLE iPhone SE (White, 128 GB)  Apple           408   
55                      APPLE iPhone SE (Red, 128 GB)  Apple           408   
57                     APPLE iPhone SE (Black, 64 GB)  Apple           350   

    MrpUSD  Discount Percentage  Number Of Ratings  Number Of Reviews  \
0      582                    0               3431                356   
5      582                    0               3431                356   
6      582                    0               3431                356   
10     558                   16              79512               6796   
52     465                   24              95807               8154   
53     523                   22              95909               8161   
54     523                   22              95807               8154   
55     523                   22              95909               8161   
57     465                   24              95909               8161   

                 Upc  Star Rating   Ram  
0   MOBEXRGV7EHHTGUH          4.6  2 GB  
5   MOBEXRGVQGYYP8FV          4.6  2 GB  
6   MOBEXRGVQKBREZP8          4.6  2 GB  
10  MOBF9Z7ZPHGV4GNH          4.6  4 GB  
52  MOBFWQ6BGWDVGF3E          4.5  2 GB  
53  MOBFWQ6BHUEVZPXD          4.5  2 GB  
54  MOBFWQ6BJEHMUUZY          4.5  2 GB  
55  MOBFWQ6BJTVFKPEJ          4.5  2 GB  
57  MOBFWQ6BR3MK7AUG          4.5  4 GB

## 8. Identifying Premium iPhones with MRP Above 1,165 USD

This code filters the dataset to find all iPhone models that have a manufacturer retail price (MRP) greater than or equal to 1,165 USD. I use this to analyze the higher-end iPhone offerings, including their product names, features, and customer ratings.

In [16]:
# Lets see if you want to find out which are all iphone that has MRP > 1,165 USD

df[df['MrpUSD']>=1165.0] 

Product Name  Brand  SalePriceUSD  \
14            APPLE iPhone 11 Pro Max (Gold, 256 GB)  Apple          1537   
15             APPLE iPhone 11 Pro Max (Gold, 64 GB)  Apple          1365   
16  APPLE iPhone 11 Pro Max (Midnight Green, 256 GB)  Apple          1537   
17       APPLE iPhone 11 Pro Max (Space Grey, 64 GB)  Apple          1365   
18       APPLE iPhone 11 Pro (Midnight Green, 64 GB)  Apple           874   
19          APPLE iPhone 11 Pro (Space Grey, 512 GB)  Apple          1374   
20   APPLE iPhone 11 Pro Max (Midnight Green, 64 GB)  Apple          1365   
21      APPLE iPhone 11 Pro (Midnight Green, 512 GB)  Apple          1374   
22          APPLE iPhone 11 Pro (Space Grey, 256 GB)  Apple          1164   
24              APPLE iPhone 12 Pro (Silver, 512 GB)  Apple          1642   
25    APPLE iPhone 12 Pro Max (Pacific Blue, 256 GB)  Apple          1526   
27            APPLE iPhone 12 Pro (Graphite, 256 GB)  Apple          1409   
30            APPLE iPhone 12 Pro (Graphite, 128 GB)  Apple          1293   
31        APPLE iPhone 12 Pro Max (Graphite, 256 GB)  Apple          1526   
32        APPLE iPhone 12 Pro Max (Graphite, 128 GB)  Apple          1409   
37          APPLE iPhone 12 Pro Max (Silver, 128 GB)  Apple          1409   
39            APPLE iPhone 12 Pro Max (Gold, 128 GB)  Apple          1409   
41        APPLE iPhone 12 Pro (Pacific Blue, 512 GB)  Apple          1642   
46        APPLE iPhone 12 Pro (Pacific Blue, 128 GB)  Apple          1293   
47    APPLE iPhone 12 Pro Max (Pacific Blue, 128 GB)  Apple          1409   
48          APPLE iPhone 12 Pro Max (Silver, 256 GB)  Apple          1526   
49            APPLE iPhone 12 Pro Max (Gold, 256 GB)  Apple          1526   

    MrpUSD  Discount Percentage  Number Of Ratings  Number Of Reviews  \
14    1537                    0               1078                101   
15    1365                    0               1078                101   
16    1537                    0               1078                101   
17    1365                    0               1078                101   
18    1243                   29               7088                523   
19    1635                   15               7088                523   
20    1365                    0               1078                101   
21    1635                   15               7088                523   
22    1414                   17               7081                522   
24    1747                    6                542                 42   
25    1631                    6                580                 45   
27    1514                    6                545                 42   
30    1398                    7                545                 42   
31    1631                    6                580                 45   
32    1514                    6                580                 45   
37    1514                    6                580                 45   
39    1514                    6                580                 45   
41    1747                    6                545                 42   
46    1398                    7                545                 42   
47    1514                    6                580                 45   
48    1631                    6                580                 45   
49    1631                    6                580                 45   

                 Upc  Star Rating   Ram  
14  MOBFKCTS7HCHSPFH          4.7  4 GB  
15  MOBFKCTSAPAYNSGG          4.7  4 GB  
16  MOBFKCTSCAAKGQV7          4.7  4 GB  
17  MOBFKCTSKDMKCGQS          4.7  4 GB  
18  MOBFKCTSN3TG3RFJ          4.6  4 GB  
19  MOBFKCTSRTHRQTFT          4.6  4 GB  
20  MOBFKCTSRYPAQNYT          4.7  4 GB  
21  MOBFKCTSSJCWYGCC          4.6  4 GB  
22  MOBFKCTSWGYSAS9X          4.6  4 GB  
24  MOBFWBYZ5UY6ZBVA          4.5  4 GB  
25  MOBFWBYZ8STJXCVT          4.6  6 GB  
27  MOBFWBYZBA36UB7G          4.5  6 GB  
30  MOBFWBYZBZ7Y56WD          4.5  6 GB  


## 9. Extracting iPhone Series/Model Name from Product Titles

This code extracts the iPhone model name (e.g., "iPhone 8", "iPhone 12") from the Product Name column and creates a cleaner, separate column for analysis. Since product titles vary in format, I use string slicing to isolate the model name and apply .strip() to remove any leading or trailing whitespace. This ensures consistent extraction whether the model name is a single digit (e.g., iPhone 8) or double digit (e.g., iPhone 12).

This step helps simplify model-wise analysis such as comparing prices, ratings, and customer engagement across different iPhone versions

In [17]:
#lets see if you want to extract iphone serires/model name from the product name and create new column name 

#df['Product Name']

#Series = one single column and if they have multiple column that becomes dataframe

##type(df['Product Name'])

#lets convert series into list

##list(df['Product Name'])

#if i do list(df['Product Name'])[0] it will give me the first product name, if you [5], it will return the fifth product name in the list
#[61] = will return the last product of the list

#list(df['Product Name'])[0]

# you can convert the product name either in upper case or lower case by doing upper() or lower()
##list(df['Product Name'])[0].upper()
##list(df['Product Name'])[0].lower()

#if you just want to extract iphone 8 from the product name you need to slice it down and for that you need to count starting from  
#0=A,1=P,2=L=3,E=4,space=5 ... count until from you want to start and continue utill you want to see the last alphabet or space

## reason i have specifically used [0] because each product will have different counting 

#list(df['Product Name'])[0][6:14]


# if the model name is ending in double digit list iphone 12 then you have to recalucate the alphabets and spaces

#list(df['Product Name'])[61][6:15]

# while adjusting the string for iphone 12 (double digit), it will create an extra space for iphone 8 (single digit) therefore
#we need to remove the white space for that we will use .strip() funtion and it will adjust the space either single or double digit

list(df['Product Name'])[61][6:15].strip()

list(df['Product Name'])[0][6:15].strip()

'iPhone 8'

## 10. Creating a New Column to Store iPhone Model Names

This code creates a new column called Model Name by extracting characters from positions 6 to 15 in the Product Name column. I use .str because the operation is applied to the entire pandas Series (not a single string), allowing string slicing across all rows. This step helps isolate the iPhone model from the full product name for easier model-based analysis.

In [20]:
#Now lets create new column , Model Name is new column name, using .str because we are convering whole list of the Product Name into string

df['Model Name'] = df['Product Name'].str[6:15]

In [19]:
#This will print first five rows of Model Name column

df['Model Name'].head()

0    iPhone 8 
1    iPhone 8 
2    iPhone 8 
3    iPhone 8 
4    iPhone 8 
Name: Model Name, dtype: object

In [21]:
# Print entire dataframe

df.head()

Product Name  Brand  SalePriceUSD  MrpUSD  \
0         APPLE iPhone 8 Plus (Gold, 64 GB)  Apple           582     582   
1  APPLE iPhone 8 Plus (Space Grey, 256 GB)  Apple           990     990   
2      APPLE iPhone 8 Plus (Silver, 256 GB)  Apple           990     990   
3           APPLE iPhone 8 (Silver, 256 GB)  Apple           898     898   
4             APPLE iPhone 8 (Gold, 256 GB)  Apple           898     898   

   Discount Percentage  Number Of Ratings  Number Of Reviews  \
0                    0               3431                356   
1                    0               3431                356   
2                    0               3431                356   
3                    0              11202                794   
4                    0              11202                794   

                Upc  Star Rating   Ram Model Name  
0  MOBEXRGV7EHHTGUH          4.6  2 GB  iPhone 8   
1  MOBEXRGVAC6TJT4F          4.6  2 GB  iPhone 8   
2  MOBEXRGVGETABXWZ          4.6  2 GB  iPhone 8   
3  MOBEXRGVMZWUHCBA          4.5  2 GB  iPhone 8   
4  MOBEXRGVPK7PFEJZ          4.5  2 GB  iPhone 8

## 11. Reordering Columns: Moving 'Model Name' Next to 'Product Name'

By default, newly created columns appear at the end of a DataFrame. This code repositions the Model Name column to appear immediately after Product Name for better readability and logical grouping. First, I remove (pop) the column, then re-insert it at index 1.

In [23]:
# Below funtion will move column Model Name next to the Product Name, usually when new column is created - it gets created
#at the end of the dataframe but with below funtion you can change the placement of column as you need.


col = df.pop('Model Name')
df.insert(1, 'Model Name', col)

In [24]:
df.head()

Product Name Model Name  Brand  SalePriceUSD  \
0         APPLE iPhone 8 Plus (Gold, 64 GB)  iPhone 8   Apple           582   
1  APPLE iPhone 8 Plus (Space Grey, 256 GB)  iPhone 8   Apple           990   
2      APPLE iPhone 8 Plus (Silver, 256 GB)  iPhone 8   Apple           990   
3           APPLE iPhone 8 (Silver, 256 GB)  iPhone 8   Apple           898   
4             APPLE iPhone 8 (Gold, 256 GB)  iPhone 8   Apple           898   

   MrpUSD  Discount Percentage  Number Of Ratings  Number Of Reviews  \
0     582                    0               3431                356   
1     990                    0               3431                356   
2     990                    0               3431                356   
3     898                    0              11202                794   
4     898                    0              11202                794   

                Upc  Star Rating   Ram  
0  MOBEXRGV7EHHTGUH          4.6  2 GB  
1  MOBEXRGVAC6TJT4F          4.6  2 GB  
2  MOBEXRGVGETABXWZ          4.6  2 GB  
3  MOBEXRGVMZWUHCBA          4.5  2 GB  
4  MOBEXRGVPK7PFEJZ          4.5  2 GB

## 12. Analyzing iPhone Models by Star Rating: Highest and Lowest

This code sorts the entire dataset based on the Star Rating column to identify which iPhone models received the highest and lowest customer ratings.

To find the highest-rated iPhones, I sort in descending order (ascending=False).

To find the lowest-rated iPhones, I sort in ascending order (ascending=True).

In [25]:
#Lets analyize the whole dataset based on which iphone has hightest and lowest reviews

#Higiest review = ascending = False
#lowest review = ascending = True


df.sort_values(by=['Star Rating'], ascending = False)
#df.sort_values(by=['Star Rating'], ascending = True) 

Product Name Model Name  Brand  \
20    APPLE iPhone 11 Pro Max (Midnight Green, 64 GB)  iPhone 11  Apple   
17        APPLE iPhone 11 Pro Max (Space Grey, 64 GB)  iPhone 11  Apple   
16   APPLE iPhone 11 Pro Max (Midnight Green, 256 GB)  iPhone 11  Apple   
15              APPLE iPhone 11 Pro Max (Gold, 64 GB)  iPhone 11  Apple   
14             APPLE iPhone 11 Pro Max (Gold, 256 GB)  iPhone 11  Apple   
..                                                ...        ...    ...   
45                APPLE iPhone 12 Mini (Black, 64 GB)  iPhone 12  Apple   
28                APPLE iPhone 12 Mini (White, 64 GB)  iPhone 12  Apple   
23  Apple iPhone SE (White, 256 GB) (Includes EarP...  iPhone SE  Apple   
41         APPLE iPhone 12 Pro (Pacific Blue, 512 GB)  iPhone 12  Apple   
27             APPLE iPhone 12 Pro (Graphite, 256 GB)  iPhone 12  Apple   

    SalePriceUSD  MrpUSD  Discount Percentage  Number Of Ratings  \
20          1365    1365                    0               1078   
17          1365    1365                    0               1078   
16          1537    1537                    0               1078   
15          1365    1365                    0               1078   
14          1537    1537                    0               1078   
..           ...     ...                  ...                ...   
45           698     815                   14                740   
28           698     815                   14                740   
23           525     640                   18              95909   
41          1642    1747                    6                545   
27          1409    1514                    6                545   

    Number Of Reviews               Upc  Star Rating   Ram  
20                101  MOBFKCTSRYPAQNYT          4.7  4 GB  
17                101  MOBFKCTSKDMKCGQS          4.7  4 GB  
16                101  MOBFKCTSCAAKGQV7          4.7  4 GB  
15                101  MOBFKCTSAPAYNSGG          4.7  4 GB  
14                101  MOBFKCTS7HCHSPFH          4.7  4 GB  
..                ...               ...          ...   ...  
45                 64  MOBFWBYZXSEGBS6F          4.5  4 GB  
28                 64  MOBFWBYZBH4CEC4C          4.5  4 GB  
23               8161  MOBFRFXHPZCHAPEH          4.5  2 GB  
41                 42  MOBFWBYZTHSXKMGW          4.5  4 GB  
27                 42  MOBFWBYZBA36UB7G          4.5  6 GB  

[62 rows x 11 columns]

## 13. Finding the Top 10 iPhone Deals Based on Discount Percentage

This code identifies the top 10 iPhone products with the highest discount percentages.

The first line (commented) returns only the Discount Percentage column as a Series, sorted in descending order.

The second line returns the entire DataFrame, sorted by Discount Percentage, so I can view all related details such as product name, brand, sale price, and rating.

In [26]:
#df['Discount Percentage'].sort_values(ascending=False).head(10)  # Top 10 deals #Series only

df.sort_values(by='Discount Percentage', ascending=False).head(10)  # Full DataFrame 


Product Name Model Name  Brand  \
18        APPLE iPhone 11 Pro (Midnight Green, 64 GB)  iPhone 11  Apple   
52                     APPLE iPhone SE (White, 64 GB)  iPhone SE  Apple   
57                     APPLE iPhone SE (Black, 64 GB)  iPhone SE  Apple   
55                      APPLE iPhone SE (Red, 128 GB)  iPhone SE  Apple   
54                    APPLE iPhone SE (White, 128 GB)  iPhone SE  Apple   
53                    APPLE iPhone SE (Black, 128 GB)  iPhone SE  Apple   
9   Apple iPhone XR ((PRODUCT)RED, 128 GB) (Includ...  iPhone XR  Apple   
11  Apple iPhone XR (Coral, 128 GB) (Includes EarP...  iPhone XR  Apple   
12  Apple iPhone XR (Black, 128 GB) (Includes EarP...  iPhone XR  Apple   
13  Apple iPhone XR (White, 128 GB) (Includes EarP...  iPhone XR  Apple   

    SalePriceUSD  MrpUSD  Discount Percentage  Number Of Ratings  \
18           874    1243                   29               7088   
52           350     465                   24              95807   
57           350     465                   24              95909   
55           408     523                   22              95909   
54           408     523                   22              95807   
53           408     523                   22              95909   
9            490     617                   20              79512   
11           490     617                   20              79582   
12           490     617                   20              79512   
13           490     617                   20              79512   

    Number Of Reviews               Upc  Star Rating   Ram  
18                523  MOBFKCTSN3TG3RFJ          4.6  4 GB  
52               8154  MOBFWQ6BGWDVGF3E          4.5  2 GB  
57               8161  MOBFWQ6BR3MK7AUG          4.5  4 GB  
55               8161  MOBFWQ6BJTVFKPEJ          4.5  2 GB  
54               8154  MOBFWQ6BJEHMUUZY          4.5  2 GB  
53               8161  MOBFWQ6BHUEVZPXD          4.5  2 GB  
9                6796  MOBF9Z7ZHQC23PWQ          4.6  4 GB  
11               6804  MOBF9Z7ZS6GF5UAP          4.6  4 GB  
12               6796  MOBF9Z7ZYWNFGZUC          4.6  3 GB  
13               6796  MOBF9Z7ZZY3HCDZZ          4.6  4 GB

## 14. Top 10 Best-Rated Yet Affordably Priced iPhones

This code sorts the entire DataFrame first by Star Rating in descending order (to prioritize best-rated products), and then by MrpUSD in ascending order (to favor lower-priced models among those highly rated).

The result highlights iPhone models that offer the best customer satisfaction while being relatively affordable, making it easier to identify top-rated models with good value for money.

In [27]:
df.sort_values(
    by=['Star Rating','MrpUSD'],
    ascending=[False, True]
).head(10)

Product Name Model Name  Brand  \
15              APPLE iPhone 11 Pro Max (Gold, 64 GB)  iPhone 11  Apple   
17        APPLE iPhone 11 Pro Max (Space Grey, 64 GB)  iPhone 11  Apple   
20    APPLE iPhone 11 Pro Max (Midnight Green, 64 GB)  iPhone 11  Apple   
14             APPLE iPhone 11 Pro Max (Gold, 256 GB)  iPhone 11  Apple   
16   APPLE iPhone 11 Pro Max (Midnight Green, 256 GB)  iPhone 11  Apple   
10  Apple iPhone XR (Black, 64 GB) (Includes EarPo...  iPhone XR  Apple   
0                   APPLE iPhone 8 Plus (Gold, 64 GB)  iPhone 8   Apple   
5                 APPLE iPhone 8 Plus (Silver, 64 GB)  iPhone 8   Apple   
6             APPLE iPhone 8 Plus (Space Grey, 64 GB)  iPhone 8   Apple   
9   Apple iPhone XR ((PRODUCT)RED, 128 GB) (Includ...  iPhone XR  Apple   

    SalePriceUSD  MrpUSD  Discount Percentage  Number Of Ratings  \
15          1365    1365                    0               1078   
17          1365    1365                    0               1078   
20          1365    1365                    0               1078   
14          1537    1537                    0               1078   
16          1537    1537                    0               1078   
10           466     558                   16              79512   
0            582     582                    0               3431   
5            582     582                    0               3431   
6            582     582                    0               3431   
9            490     617                   20              79512   

    Number Of Reviews               Upc  Star Rating   Ram  
15                101  MOBFKCTSAPAYNSGG          4.7  4 GB  
17                101  MOBFKCTSKDMKCGQS          4.7  4 GB  
20                101  MOBFKCTSRYPAQNYT          4.7  4 GB  
14                101  MOBFKCTS7HCHSPFH          4.7  4 GB  
16                101  MOBFKCTSCAAKGQV7          4.7  4 GB  
10               6796  MOBF9Z7ZPHGV4GNH          4.6  4 GB  
0                 356  MOBEXRGV7EHHTGUH          4.6  2 GB  
5                 356  MOBEXRGVQGYYP8FV          4.6  2 GB  
6                 356  MOBEXRGVQKBREZP8          4.6  2 GB  
9                6796  MOBF9Z7ZHQC23PWQ          4.6  4 GB

In [28]:
#Finding out the Hightest Number of Reviews

df['Number Of Ratings'].max()

95909

In [29]:
#Finding out the Model Name that has highest Number of Reviews

df[df['Number Of Ratings'] == 95909] 

Product Name Model Name  Brand  \
23  Apple iPhone SE (White, 256 GB) (Includes EarP...  iPhone SE  Apple   
53                    APPLE iPhone SE (Black, 128 GB)  iPhone SE  Apple   
55                      APPLE iPhone SE (Red, 128 GB)  iPhone SE  Apple   
57                     APPLE iPhone SE (Black, 64 GB)  iPhone SE  Apple   

    SalePriceUSD  MrpUSD  Discount Percentage  Number Of Ratings  \
23           525     640                   18              95909   
53           408     523                   22              95909   
55           408     523                   22              95909   
57           350     465                   24              95909   

    Number Of Reviews               Upc  Star Rating   Ram  
23               8161  MOBFRFXHPZCHAPEH          4.5  2 GB  
53               8161  MOBFWQ6BHUEVZPXD          4.5  2 GB  
55               8161  MOBFWQ6BJTVFKPEJ          4.5  2 GB  
57               8161  MOBFWQ6BR3MK7AUG          4.5  4 GB