# Step-by-Step Analysis and Insights from Artrya’s Primary Dataset

## Introduction

📌 Purpose of Analysis
The purpose of this analysis is to gain insights into pricing, discount strategies, customer engagement, and product performance across various Apple products. Using Python, we explore key attributes such as sale price, MRP, discount percentage, star rating, number of reviews, and RAM specifications to:

Identify top discounted products and pricing trends

Evaluate brand-wise product performance

Understand customer preferences based on ratings and reviews

Uncover correlations between pricing, ratings, and technical specs

This data-driven approach supports better decision-making for marketing, pricing optimization, and inventory planning.

## 1. Reading the csv file  (apple_products_usd.csv)

In [1]:
import pandas as pd


In [30]:
df = pd.read_csv("D:/Darshil Parmar - DE/Python/python-for-data-engineering-main/python-for-data-engineering-main/1. iPhone Data Analysis Project/Data/apple_products_usd.csv")


#### You may encounter the error if you use backward slashes 

The issue with your code is likely due to how the file path is written on Windows. Specifically, you’re using backslashes (\) in the file path, and in Python strings, a backslash is treated as an escape character.

🔧 Problem:
python
Copy
Edit
"D:\Darshil Parmar - DE\Python\python-for-data-engineering-main\..."
In this path, \D, \P, etc. are interpreted as escape sequences (e.g., \n = newline, \t = tab), which causes a FileNotFoundError or unexpected behavior.

✅ Solutions:                                                                                                                    Use forward slashes (even on Windows)
df = pd.read_csv("D:/Darshil Parmar - DE/Python/python-for-data-engineering-main/python-for-data-engineering-main/1. iPhone Data Analysis Project/Data/apple_products.csv")

Use double backslashes
df = pd.read_csv("D:\\Darshil Parmar - DE\\Python\\python-for-data-engineering-main\\python-for-data-engineering-main\\1. iPhone Data Analysis Project\\Data\\apple_products.csv")



In [98]:
# below funtion will print first five rows of the csv file
df.head()

Product Name Model Name  \
0         APPLE iPhone 8 Plus (Gold, 64 GB)  iPhone 8    
1  APPLE iPhone 8 Plus (Space Grey, 256 GB)  iPhone 8    
2      APPLE iPhone 8 Plus (Silver, 256 GB)  iPhone 8    
3           APPLE iPhone 8 (Silver, 256 GB)  iPhone 8    
4             APPLE iPhone 8 (Gold, 256 GB)  iPhone 8    

                                         Product URL  Brand  SalePriceUSD  \
0  https://www.flipkart.com/apple-iphone-8-plus-g...  Apple         582.0   
1  https://www.flipkart.com/apple-iphone-8-plus-s...  Apple         990.0   
2  https://www.flipkart.com/apple-iphone-8-plus-s...  Apple         990.0   
3  https://www.flipkart.com/apple-iphone-8-silver...  Apple         898.0   
4  https://www.flipkart.com/apple-iphone-8-gold-2...  Apple         898.0   

   MrpUSD  Discount Percentage  Number Of Ratings  Number Of Reviews  \
0   582.0                    0               3431                356   
1   990.0                    0               3431                356   
2   990.0                    0               3431                356   
3   898.0                    0              11202                794   
4   898.0                    0              11202                794   

                Upc  Star Rating   Ram  
0  MOBEXRGV7EHHTGUH          4.6  2 GB  
1  MOBEXRGVAC6TJT4F          4.6  2 GB  
2  MOBEXRGVGETABXWZ          4.6  2 GB  
3  MOBEXRGVMZWUHCBA          4.5  2 GB  
4  MOBEXRGVPK7PFEJZ          4.5  2 GB

 Calculating the total rows for each column

## 2.  Checking the Number of Records per Column

In [ ]:
# Lets find out how big is the file

df.count()

## 3. Identifying the Highest Listed Price (MRP) in USD

In [32]:
#lets find out the highest MRP (all prices are tagged in USD)

df['MrpUSD'].max()

1747.0

## 4. Identifying the Lowest Listed Price (MRP) in USD

In [33]:
#lets find out the lowest or minimum MRP (all prices are tagged in USD)

df['MrpUSD'].min()

465.0

## 5. Finding the iPhone Model with the Highest MRP

This code identifies the iPhone that was listed at the highest manufacturer retail price (MRP) in the dataset. By filtering the DataFrame for the maximum MRP value (1747.0 USD), I retrieve the full product details — including the product name, brand, rating, and other attributes — for the highest-priced iPhone.

In [36]:
#Lets figuer out which iphone was sold at the highest price (meaning Product name)

df[df['MrpUSD']==1747.0] 

Product Name  \
24        APPLE iPhone 12 Pro (Silver, 512 GB)   
41  APPLE iPhone 12 Pro (Pacific Blue, 512 GB)   

                                          Product URL  Brand  SalePriceUSD  \
24  https://www.flipkart.com/apple-iphone-12-pro-s...  Apple        1642.0   
41  https://www.flipkart.com/apple-iphone-12-pro-p...  Apple        1642.0   

    MrpUSD  Discount Percentage  Number Of Ratings  Number Of Reviews  \
24  1747.0                    6                542                 42   
41  1747.0                    6                545                 42   

                 Upc  Star Rating   Ram  
24  MOBFWBYZ5UY6ZBVA          4.5  4 GB  
41  MOBFWBYZTHSXKMGW          4.5  4 GB

## 6. Finding the iPhone Model with the Lowest MRP

This code is used to find the iPhone that was listed at the lowest manufacturer retail price (MRP) in the dataset. By filtering the DataFrame for the minimum MRP value (465.0 USD), I extract the complete product details — including the product name, brand, rating, and specifications — for the most affordable iPhone in the dataset.

In [37]:
#Lets figuer out which iphone was sold at the lowest price (meaning Product name)

df[df['MrpUSD']==465.0]

Product Name  \
52  APPLE iPhone SE (White, 64 GB)   
57  APPLE iPhone SE (Black, 64 GB)   

                                          Product URL  Brand  SalePriceUSD  \
52  https://www.flipkart.com/apple-iphone-se-white...  Apple         350.0   
57  https://www.flipkart.com/apple-iphone-se-black...  Apple         350.0   

    MrpUSD  Discount Percentage  Number Of Ratings  Number Of Reviews  \
52   465.0                   24              95807               8154   
57   465.0                   24              95909               8161   

                 Upc  Star Rating   Ram  
52  MOBFWQ6BGWDVGF3E          4.5  2 GB  
57  MOBFWQ6BR3MK7AUG          4.5  4 GB

## 7. Listing All iPhones Priced Below 600 USD (MRP)

This code filters the dataset to identify all iPhone models with a manufacturer retail price (MRP) less than or equal to 600 USD. I use this to explore more budget-friendly options and analyze the features, ratings, and other details of lower-priced iPhones.

In [40]:
# Lets see if you want to find out which are all iphone that has MRP < 500 USD

df[df['MrpUSD']<=600.0]

Product Name  \
0                   APPLE iPhone 8 Plus (Gold, 64 GB)   
5                 APPLE iPhone 8 Plus (Silver, 64 GB)   
6             APPLE iPhone 8 Plus (Space Grey, 64 GB)   
10  Apple iPhone XR (Black, 64 GB) (Includes EarPo...   
52                     APPLE iPhone SE (White, 64 GB)   
53                    APPLE iPhone SE (Black, 128 GB)   
54                    APPLE iPhone SE (White, 128 GB)   
55                      APPLE iPhone SE (Red, 128 GB)   
57                     APPLE iPhone SE (Black, 64 GB)   

                                          Product URL  Brand  SalePriceUSD  \
0   https://www.flipkart.com/apple-iphone-8-plus-g...  Apple         582.0   
5   https://www.flipkart.com/apple-iphone-8-plus-s...  Apple         582.0   
6   https://www.flipkart.com/apple-iphone-8-plus-s...  Apple         582.0   
10  https://www.flipkart.com/apple-iphone-xr-black...  Apple         466.0   
52  https://www.flipkart.com/apple-iphone-se-white...  Apple         350.0   
53  https://www.flipkart.com/apple-iphone-se-black...  Apple         408.0   
54  https://www.flipkart.com/apple-iphone-se-white...  Apple         408.0   
55  https://www.flipkart.com/apple-iphone-se-red-1...  Apple         408.0   
57  https://www.flipkart.com/apple-iphone-se-black...  Apple         350.0   

    MrpUSD  Discount Percentage  Number Of Ratings  Number Of Reviews  \
0    582.0                    0               3431                356   
5    582.0                    0               3431                356   
6    582.0                    0               3431                356   
10   558.0                   16              79512               6796   
52   465.0                   24              95807               8154   
53   523.0                   22              95909               8161   
54   523.0                   22              95807               8154   
55   523.0                   22              95909               8161   
57   465.0                   24              95909               8161   

                 Upc  Star Rating   Ram  
0   MOBEXRGV7EHHTGUH          4.6  2 GB  
5   MOBEXRGVQGYYP8FV          4.6  2 GB  
6   MOBEXRGVQKBREZP8          4.6  2 GB  
10  MOBF9Z7ZPHGV4GNH          4.6  4 GB  
52  MOBFWQ6BGWDVGF3E          4.5  2 GB  
53  MOBFWQ6BHUEVZPXD          4.5  2 GB  
54  MOBFWQ6BJEHMUUZY          4.5  2 GB  
55  MOBFWQ6BJTVFKPEJ          4.5  2 GB  
57  MOBFWQ6BR3MK7AUG          4.5  4 GB

## 8. Identifying Premium iPhones with MRP Above 1,165 USD

This code filters the dataset to find all iPhone models that have a manufacturer retail price (MRP) greater than or equal to 1,165 USD. I use this to analyze the higher-end iPhone offerings, including their product names, features, and customer ratings.

In [41]:
# Lets see if you want to find out which are all iphone that has MRP > 1,165 USD

df[df['MrpUSD']>=1165.0] 

Product Name  \
14            APPLE iPhone 11 Pro Max (Gold, 256 GB)   
15             APPLE iPhone 11 Pro Max (Gold, 64 GB)   
16  APPLE iPhone 11 Pro Max (Midnight Green, 256 GB)   
17       APPLE iPhone 11 Pro Max (Space Grey, 64 GB)   
18       APPLE iPhone 11 Pro (Midnight Green, 64 GB)   
19          APPLE iPhone 11 Pro (Space Grey, 512 GB)   
20   APPLE iPhone 11 Pro Max (Midnight Green, 64 GB)   
21      APPLE iPhone 11 Pro (Midnight Green, 512 GB)   
22          APPLE iPhone 11 Pro (Space Grey, 256 GB)   
24              APPLE iPhone 12 Pro (Silver, 512 GB)   
25    APPLE iPhone 12 Pro Max (Pacific Blue, 256 GB)   
27            APPLE iPhone 12 Pro (Graphite, 256 GB)   
30            APPLE iPhone 12 Pro (Graphite, 128 GB)   
31        APPLE iPhone 12 Pro Max (Graphite, 256 GB)   
32        APPLE iPhone 12 Pro Max (Graphite, 128 GB)   
37          APPLE iPhone 12 Pro Max (Silver, 128 GB)   
39            APPLE iPhone 12 Pro Max (Gold, 128 GB)   
41        APPLE iPhone 12 Pro (Pacific Blue, 512 GB)   
46        APPLE iPhone 12 Pro (Pacific Blue, 128 GB)   
47    APPLE iPhone 12 Pro Max (Pacific Blue, 128 GB)   
48          APPLE iPhone 12 Pro Max (Silver, 256 GB)   
49            APPLE iPhone 12 Pro Max (Gold, 256 GB)   

                                          Product URL  Brand  SalePriceUSD  \
14  https://www.flipkart.com/apple-iphone-11-pro-m...  Apple        1537.0   
15  https://www.flipkart.com/apple-iphone-11-pro-m...  Apple        1365.0   
16  https://www.flipkart.com/apple-iphone-11-pro-m...  Apple        1537.0   
17  https://www.flipkart.com/apple-iphone-11-pro-m...  Apple        1365.0   
18  https://www.flipkart.com/apple-iphone-11-pro-m...  Apple         874.0   
19  https://www.flipkart.com/apple-iphone-11-pro-s...  Apple        1374.0   
20  https://www.flipkart.com/apple-iphone-11-pro-m...  Apple        1365.0   
21  https://www.flipkart.com/apple-iphone-11-pro-m...  Apple        1374.0   
22  https://www.flipkart.com/apple-iphone-11-pro-s...  Apple        1164.0   
24  https://www.flipkart.com/apple-iphone-12-pro-s...  Apple        1642.0   
25  https://www.flipkart.com/apple-iphone-12-pro-m...  Apple        1526.0   
27  https://www.flipkart.com/apple-iphone-12-pro-g...  Apple        1409.0   
30  https://www.flipkart.com/apple-iphone-12-pro-g...  Apple        1293.0   
31  https://www.flipkart.com/apple-iphone-12-pro-m...  Apple        1526.0   
32  https://www.flipkart.com/apple-iphone-12-pro-m...  Apple        1409.0   
37  https://www.flipkart.com/apple-iphone-12-pro-m...  Apple        1409.0   
39  https://www.flipkart.com/apple-iphone-12-pro-m...  Apple        1409.0   
41  https://www.flipkart.com/apple-iphone-12-pro-p...  Apple        1642.0   
46  https://www.flipkart.com/apple-iphone-12-pro-p...  Apple        1293.0   
47  https://www.flipkart.com/apple-iphone-12-pro-m...  Apple        1409.0   
48  https://www.flipkart.com/apple-iphone-12-pro-m...  Apple        1526.0   
49  https://www.flipkart.com/apple-iphone-12-pro-m...  Apple        1526.0   

    MrpUSD  Discount Percentage  Number Of Ratings  Number Of Reviews  \
14  1537.0                    0               1078                101   
15  1365.0                    0               1078                101   
16  1537.0                    0               1078                101   
17  1365.0                    0               1078                101   
18  1243.0                   29               7088                523   
19  1635.0                   15               7088                523   
20  1365.0                    0               1078                101   
21  1635.0                   15               7088                523   
22  1414.0                   17               7081                522   
24  1747.0                    6                542                 42   
25  1631.0                    6                580                 45   
27  1514.0                    6                545                 42   
30  139

## 9. Extracting iPhone Series/Model Name from Product Titles

This code extracts the iPhone model name (e.g., "iPhone 8", "iPhone 12") from the Product Name column and creates a cleaner, separate column for analysis. Since product titles vary in format, I use string slicing to isolate the model name and apply .strip() to remove any leading or trailing whitespace. This ensures consistent extraction whether the model name is a single digit (e.g., iPhone 8) or double digit (e.g., iPhone 12).

This step helps simplify model-wise analysis such as comparing prices, ratings, and customer engagement across different iPhone versions

In [65]:
#lets see if you want to extract iphone serires/model name from the product name and create new column name 

#df['Product Name']

#Series = one single column and if they have multiple column that becomes dataframe

##type(df['Product Name'])

#lets convert series into list

##list(df['Product Name'])

#if i do list(df['Product Name'])[0] it will give me the first product name, if you [5], it will return the fifth product name in the list
#[61] = will return the last product of the list

#list(df['Product Name'])[0]

# you can convert the product name either in upper case or lower case by doing upper() or lower()
##list(df['Product Name'])[0].upper()
##list(df['Product Name'])[0].lower()

#if you just want to extract iphone 8 from the product name you need to slice it down and for that you need to count starting from  
#0=A,1=P,2=L=3,E=4,space=5 ... count until from you want to start and continue utill you want to see the last alphabet or space

## reason i have specifically used [0] because each product will have different counting 

#list(df['Product Name'])[0][6:14]


# if the model name is ending in double digit list iphone 12 then you have to recalucate the alphabets and spaces

#list(df['Product Name'])[61][6:15]

# while adjusting the string for iphone 12 (double digit), it will create an extra space for iphone 8 (single digit) therefore
#we need to remove the white space for that we will use .strip() funtion and it will adjust the space either single or double digit

list(df['Product Name'])[61][6:15].strip()

list(df['Product Name'])[0][6:15].strip()

'iPhone 8'

## 10. Creating a New Column to Store iPhone Model Names

This code creates a new column called Model Name by extracting characters from positions 6 to 15 in the Product Name column. I use .str because the operation is applied to the entire pandas Series (not a single string), allowing string slicing across all rows. This step helps isolate the iPhone model from the full product name for easier model-based analysis.

In [86]:
#Now lets create new column , Model Name is new column name, using .str because we are convering whole list of the Product Name into string

df['Model Name'] = df['Product Name'].str[6:15]

In [70]:
#This will print first five rows of Model Name column

df['Model Name'].head()

0    iPhone 8 
1    iPhone 8 
2    iPhone 8 
3    iPhone 8 
4    iPhone 8 
Name: Model Name, dtype: object

In [87]:
# Print entire dataframe

df.head()

Product Name Model Name  \
0         APPLE iPhone 8 Plus (Gold, 64 GB)  iPhone 8    
1  APPLE iPhone 8 Plus (Space Grey, 256 GB)  iPhone 8    
2      APPLE iPhone 8 Plus (Silver, 256 GB)  iPhone 8    
3           APPLE iPhone 8 (Silver, 256 GB)  iPhone 8    
4             APPLE iPhone 8 (Gold, 256 GB)  iPhone 8    

                                         Product URL  Brand  SalePriceUSD  \
0  https://www.flipkart.com/apple-iphone-8-plus-g...  Apple         582.0   
1  https://www.flipkart.com/apple-iphone-8-plus-s...  Apple         990.0   
2  https://www.flipkart.com/apple-iphone-8-plus-s...  Apple         990.0   
3  https://www.flipkart.com/apple-iphone-8-silver...  Apple         898.0   
4  https://www.flipkart.com/apple-iphone-8-gold-2...  Apple         898.0   

   MrpUSD  Discount Percentage  Number Of Ratings  Number Of Reviews  \
0   582.0                    0               3431                356   
1   990.0                    0               3431                356   
2   990.0                    0               3431                356   
3   898.0                    0              11202                794   
4   898.0                    0              11202                794   

                Upc  Star Rating   Ram  
0  MOBEXRGV7EHHTGUH          4.6  2 GB  
1  MOBEXRGVAC6TJT4F          4.6  2 GB  
2  MOBEXRGVGETABXWZ          4.6  2 GB  
3  MOBEXRGVMZWUHCBA          4.5  2 GB  
4  MOBEXRGVPK7PFEJZ          4.5  2 GB

## 11. Reordering Columns: Moving 'Model Name' Next to 'Product Name'

By default, newly created columns appear at the end of a DataFrame. This code repositions the Model Name column to appear immediately after Product Name for better readability and logical grouping. First, I remove (pop) the column, then re-insert it at index 1.

In [88]:
# Below funtion will move column Model Name next to the Product Name, usually when new column is created - it gets created
#at the end of the dataframe but with below funtion you can change the placement of column as you need.


col = df.pop('Model Name')
df.insert(1, 'Model Name', col)

In [77]:
df.head()

Product Name Model Name  \
0         APPLE iPhone 8 Plus (Gold, 64 GB)  iPhone 8    
1  APPLE iPhone 8 Plus (Space Grey, 256 GB)  iPhone 8    
2      APPLE iPhone 8 Plus (Silver, 256 GB)  iPhone 8    
3           APPLE iPhone 8 (Silver, 256 GB)  iPhone 8    
4             APPLE iPhone 8 (Gold, 256 GB)  iPhone 8    

                                         Product URL  Brand  SalePriceUSD  \
0  https://www.flipkart.com/apple-iphone-8-plus-g...  Apple         582.0   
1  https://www.flipkart.com/apple-iphone-8-plus-s...  Apple         990.0   
2  https://www.flipkart.com/apple-iphone-8-plus-s...  Apple         990.0   
3  https://www.flipkart.com/apple-iphone-8-silver...  Apple         898.0   
4  https://www.flipkart.com/apple-iphone-8-gold-2...  Apple         898.0   

   MrpUSD  Discount Percentage  Number Of Ratings  Number Of Reviews  \
0   582.0                    0               3431                356   
1   990.0                    0               3431                356   
2   990.0                    0               3431                356   
3   898.0                    0              11202                794   
4   898.0                    0              11202                794   

                Upc  Star Rating   Ram  
0  MOBEXRGV7EHHTGUH          4.6  2 GB  
1  MOBEXRGVAC6TJT4F          4.6  2 GB  
2  MOBEXRGVGETABXWZ          4.6  2 GB  
3  MOBEXRGVMZWUHCBA          4.5  2 GB  
4  MOBEXRGVPK7PFEJZ          4.5  2 GB

## 12. Analyzing iPhone Models by Star Rating: Highest and Lowest

This code sorts the entire dataset based on the Star Rating column to identify which iPhone models received the highest and lowest customer ratings.

To find the highest-rated iPhones, I sort in descending order (ascending=False).

To find the lowest-rated iPhones, I sort in ascending order (ascending=True).

In [94]:
#Lets analyize the whole dataset based on which iphone has hightest and lowest reviews

#Higiest review = ascending = False
#lowest review = ascending = True


df.sort_values(by=['Star Rating'], ascending = False)
#df.sort_values(by=['Star Rating'], ascending = True) 

Product Name Model Name  \
20    APPLE iPhone 11 Pro Max (Midnight Green, 64 GB)  iPhone 11   
17        APPLE iPhone 11 Pro Max (Space Grey, 64 GB)  iPhone 11   
16   APPLE iPhone 11 Pro Max (Midnight Green, 256 GB)  iPhone 11   
15              APPLE iPhone 11 Pro Max (Gold, 64 GB)  iPhone 11   
14             APPLE iPhone 11 Pro Max (Gold, 256 GB)  iPhone 11   
..                                                ...        ...   
45                APPLE iPhone 12 Mini (Black, 64 GB)  iPhone 12   
28                APPLE iPhone 12 Mini (White, 64 GB)  iPhone 12   
23  Apple iPhone SE (White, 256 GB) (Includes EarP...  iPhone SE   
41         APPLE iPhone 12 Pro (Pacific Blue, 512 GB)  iPhone 12   
27             APPLE iPhone 12 Pro (Graphite, 256 GB)  iPhone 12   

                                          Product URL  Brand  SalePriceUSD  \
20  https://www.flipkart.com/apple-iphone-11-pro-m...  Apple        1365.0   
17  https://www.flipkart.com/apple-iphone-11-pro-m...  Apple        1365.0   
16  https://www.flipkart.com/apple-iphone-11-pro-m...  Apple        1537.0   
15  https://www.flipkart.com/apple-iphone-11-pro-m...  Apple        1365.0   
14  https://www.flipkart.com/apple-iphone-11-pro-m...  Apple        1537.0   
..                                                ...    ...           ...   
45  https://www.flipkart.com/apple-iphone-12-mini-...  Apple         698.0   
28  https://www.flipkart.com/apple-iphone-12-mini-...  Apple         698.0   
23  https://www.flipkart.com/apple-iphone-se-white...  Apple         525.0   
41  https://www.flipkart.com/apple-iphone-12-pro-p...  Apple        1642.0   
27  https://www.flipkart.com/apple-iphone-12-pro-g...  Apple        1409.0   

    MrpUSD  Discount Percentage  Number Of Ratings  Number Of Reviews  \
20  1365.0                    0               1078                101   
17  1365.0                    0               1078                101   
16  1537.0                    0               1078                101   
15  1365.0                    0               1078                101   
14  1537.0                    0               1078                101   
..     ...                  ...                ...                ...   
45   815.0                   14                740                 64   
28   815.0                   14                740                 64   
23   640.0                   18              95909               8161   
41  1747.0                    6                545                 42   
27  1514.0                    6                545                 42   

                 Upc  Star Rating   Ram  
20  MOBFKCTSRYPAQNYT          4.7  4 GB  
17  MOBFKCTSKDMKCGQS          4.7  4 GB  
16  MOBFKCTSCAAKGQV7          4.7  4 GB  
15  MOBFKCTSAPAYNSGG          4.7  4 GB  
14  MOBFKCTS7HCHSPFH          4.7  4 GB  
..               ...          ...   ...  
45  MOBFWBYZXSEGBS6F          4.5  4 GB  
28  MOBFWBYZBH4CEC4C          4.5  4 GB  
23  MOBFRFXHPZCHAPEH          4.5  2 GB  
41  MOBFWBYZTHSXKMGW          4.5  4 GB  
27  MOBFWBYZBA36UB7G          4.5  6 GB  

[62 rows x 12 columns]

## 13. Finding the Top 10 iPhone Deals Based on Discount Percentage

This code identifies the top 10 iPhone products with the highest discount percentages.

The first line (commented) returns only the Discount Percentage column as a Series, sorted in descending order.

The second line returns the entire DataFrame, sorted by Discount Percentage, so I can view all related details such as product name, brand, sale price, and rating.

In [97]:
#df['Discount Percentage'].sort_values(ascending=False).head(10)  # Top 10 deals #Series only

df.sort_values(by='Discount Percentage', ascending=False).head(10)  # Full DataFrame 


Product Name Model Name  \
0                  APPLE iPhone 8 Plus (Gold, 64 GB)  iPhone 8    
15             APPLE iPhone 11 Pro Max (Gold, 64 GB)  iPhone 11   
14            APPLE iPhone 11 Pro Max (Gold, 256 GB)  iPhone 11   
20   APPLE iPhone 11 Pro Max (Midnight Green, 64 GB)  iPhone 11   
16  APPLE iPhone 11 Pro Max (Midnight Green, 256 GB)  iPhone 11   
7                APPLE iPhone 8 (Space Grey, 256 GB)  iPhone 8    
8                APPLE iPhone XS Max (Silver, 64 GB)  iPhone XS   
5                APPLE iPhone 8 Plus (Silver, 64 GB)  iPhone 8    
4                      APPLE iPhone 8 (Gold, 256 GB)  iPhone 8    
3                    APPLE iPhone 8 (Silver, 256 GB)  iPhone 8    

                                          Product URL  Brand  SalePriceUSD  \
0   https://www.flipkart.com/apple-iphone-8-plus-g...  Apple         582.0   
15  https://www.flipkart.com/apple-iphone-11-pro-m...  Apple        1365.0   
14  https://www.flipkart.com/apple-iphone-11-pro-m...  Apple        1537.0   
20  https://www.flipkart.com/apple-iphone-11-pro-m...  Apple        1365.0   
16  https://www.flipkart.com/apple-iphone-11-pro-m...  Apple        1537.0   
7   https://www.flipkart.com/apple-iphone-8-space-...  Apple         898.0   
8   https://www.flipkart.com/apple-iphone-xs-max-s...  Apple        1048.0   
5   https://www.flipkart.com/apple-iphone-8-plus-s...  Apple         582.0   
4   https://www.flipkart.com/apple-iphone-8-gold-2...  Apple         898.0   
3   https://www.flipkart.com/apple-iphone-8-silver...  Apple         898.0   

    MrpUSD  Discount Percentage  Number Of Ratings  Number Of Reviews  \
0    582.0                    0               3431                356   
15  1365.0                    0               1078                101   
14  1537.0                    0               1078                101   
20  1365.0                    0               1078                101   
16  1537.0                    0               1078                101   
7    898.0                    0              11202                794   
8   1048.0                    0               1454                149   
5    582.0                    0               3431                356   
4    898.0                    0              11202                794   
3    898.0                    0              11202                794   

                 Upc  Star Rating   Ram  
0   MOBEXRGV7EHHTGUH          4.6  2 GB  
15  MOBFKCTSAPAYNSGG          4.7  4 GB  
14  MOBFKCTS7HCHSPFH          4.7  4 GB  
20  MOBFKCTSRYPAQNYT          4.7  4 GB  
16  MOBFKCTSCAAKGQV7          4.7  4 GB  
7   MOBEXRGVZFZGZEWV          4.5  2 GB  
8   MOBF944E2XAHW8V5          4.6  4 GB  
5   MOBEXRGVQGYYP8FV          4.6  2 GB  
4   MOBEXRGVPK7PFEJZ          4.5  2 GB  
3   MOBEXRGVMZWUHCBA          4.5  2 GB

## 14. Top 10 Best-Rated Yet Affordably Priced iPhones

This code sorts the entire DataFrame first by Star Rating in descending order (to prioritize best-rated products), and then by MrpUSD in ascending order (to favor lower-priced models among those highly rated).

The result highlights iPhone models that offer the best customer satisfaction while being relatively affordable, making it easier to identify top-rated models with good value for money.

In [119]:
df.sort_values(
    by=['Star Rating','MrpUSD'],
    ascending=[False, True]
).head(10)

Product Name Model Name  \
15              APPLE iPhone 11 Pro Max (Gold, 64 GB)  iPhone 11   
17        APPLE iPhone 11 Pro Max (Space Grey, 64 GB)  iPhone 11   
20    APPLE iPhone 11 Pro Max (Midnight Green, 64 GB)  iPhone 11   
14             APPLE iPhone 11 Pro Max (Gold, 256 GB)  iPhone 11   
16   APPLE iPhone 11 Pro Max (Midnight Green, 256 GB)  iPhone 11   
10  Apple iPhone XR (Black, 64 GB) (Includes EarPo...  iPhone XR   
0                   APPLE iPhone 8 Plus (Gold, 64 GB)  iPhone 8    
5                 APPLE iPhone 8 Plus (Silver, 64 GB)  iPhone 8    
6             APPLE iPhone 8 Plus (Space Grey, 64 GB)  iPhone 8    
9   Apple iPhone XR ((PRODUCT)RED, 128 GB) (Includ...  iPhone XR   

                                          Product URL  Brand  SalePriceUSD  \
15  https://www.flipkart.com/apple-iphone-11-pro-m...  Apple        1365.0   
17  https://www.flipkart.com/apple-iphone-11-pro-m...  Apple        1365.0   
20  https://www.flipkart.com/apple-iphone-11-pro-m...  Apple        1365.0   
14  https://www.flipkart.com/apple-iphone-11-pro-m...  Apple        1537.0   
16  https://www.flipkart.com/apple-iphone-11-pro-m...  Apple        1537.0   
10  https://www.flipkart.com/apple-iphone-xr-black...  Apple         466.0   
0   https://www.flipkart.com/apple-iphone-8-plus-g...  Apple         582.0   
5   https://www.flipkart.com/apple-iphone-8-plus-s...  Apple         582.0   
6   https://www.flipkart.com/apple-iphone-8-plus-s...  Apple         582.0   
9   https://www.flipkart.com/apple-iphone-xr-produ...  Apple         490.0   

    MrpUSD  Discount Percentage  Number Of Ratings  Number Of Reviews  \
15  1365.0                    0               1078                101   
17  1365.0                    0               1078                101   
20  1365.0                    0               1078                101   
14  1537.0                    0               1078                101   
16  1537.0                    0               1078                101   
10   558.0                   16              79512               6796   
0    582.0                    0               3431                356   
5    582.0                    0               3431                356   
6    582.0                    0               3431                356   
9    617.0                   20              79512               6796   

                 Upc  Star Rating   Ram  
15  MOBFKCTSAPAYNSGG          4.7  4 GB  
17  MOBFKCTSKDMKCGQS          4.7  4 GB  
20  MOBFKCTSRYPAQNYT          4.7  4 GB  
14  MOBFKCTS7HCHSPFH          4.7  4 GB  
16  MOBFKCTSCAAKGQV7          4.7  4 GB  
10  MOBF9Z7ZPHGV4GNH          4.6  4 GB  
0   MOBEXRGV7EHHTGUH          4.6  2 GB  
5   MOBEXRGVQGYYP8FV          4.6  2 GB  
6   MOBEXRGVQKBREZP8          4.6  2 GB  
9   MOBF9Z7ZHQC23PWQ          4.6  4 GB

In [121]:
#Finding out the Hightest Number of Reviews

df['Number Of Ratings'].max()

95909

In [120]:
#Finding out the Model Name that has highest Number of Reviews

df[df['Number Of Ratings'] == 95909] 

Product Name Model Name  \
23  Apple iPhone SE (White, 256 GB) (Includes EarP...  iPhone SE   
53                    APPLE iPhone SE (Black, 128 GB)  iPhone SE   
55                      APPLE iPhone SE (Red, 128 GB)  iPhone SE   
57                     APPLE iPhone SE (Black, 64 GB)  iPhone SE   

                                          Product URL  Brand  SalePriceUSD  \
23  https://www.flipkart.com/apple-iphone-se-white...  Apple         525.0   
53  https://www.flipkart.com/apple-iphone-se-black...  Apple         408.0   
55  https://www.flipkart.com/apple-iphone-se-red-1...  Apple         408.0   
57  https://www.flipkart.com/apple-iphone-se-black...  Apple         350.0   

    MrpUSD  Discount Percentage  Number Of Ratings  Number Of Reviews  \
23   640.0                   18              95909               8161   
53   523.0                   22              95909               8161   
55   523.0                   22              95909               8161   
57   465.0                   24              95909               8161   

                 Upc  Star Rating   Ram  
23  MOBFRFXHPZCHAPEH          4.5  2 GB  
53  MOBFWQ6BHUEVZPXD          4.5  2 GB  
55  MOBFWQ6BJTVFKPEJ          4.5  2 GB  
57  MOBFWQ6BR3MK7AUG          4.5  4 GB